components/final.js, games/christmas.json, pages/admin.js, pages/new.js, server.js
can go back to final round 1
gamecreator saves int instead of string for  points
final  round points and  selections are preserved.
=> a bunch of ux tweaks for better final rounds

components/Admin/players.js, components/admin.js, pages/index.js, server.js
- can quit player from admin
- don't clear room code on main page
=> team viewer/kicker component

pages/new.js
- Prevent unloading the page losing work
- separate game data from theme data so game load doesn't clear theme
- move the load game dialog to top of page
=> New game page protect losing settings

components/admin.js, components/buzzer.js, pages/api/ws.js, pages/game.js
Shows the X on the game screen and on the buzzer screen for 2 seconds. 
Run some of the files through prettier
=> New button to "show" a mistake happened without counting towards a team.

components/Admin/settings.js, i18n/i18n.js, i18n/i18next-scanner.config.js
Declaration of french language inside i18n module
=> french language declaration on i18n module

components/buzzer.js, pages/api/ws.js, pages/game.js
This allows joining players to enter a "spectator" mode which is just the same "/game" screen that the admin has access to, but from the joining player.
In this mode a "quit" button is shown for the joining player.
=> Game window on buzzer

components/Admin/csv-loader.js, components/Admin/players.js, components/Admin/settings.js, components/admin.js, components/buzzer.js, components/final.js, components/question-board.js, components/title-logo.js, components/title.js, games/et/jõulueri-2020.json, pages/api/ws.js, pages/new.js, public/locales/en/translation.json, public/locales/et/translation.json
**Description:**
Browser console had multiple various errors I noticed, this fixes most of them, but I will leave other more complicated fixes for another PR since this one is getting a bit big
**Changes made:**
1654a54450e7caf72fff83f86f9868a40ea323b7 solves a hydration issue with the dynamic SVG logo
3602507aa6847eda19256d72586f68ea9880692c fixes an issue I created where the SVG logo on game screen disappeared due to not having a set height and width
f61b722fc7aaa766e68d2e143f7e9563782542d0 solves the React warning for impartial useEffect cleanups
bd62b3180b553310d6ceb85e1adef76858aba3c4 solves a UX issue, where we shouldn't send "host quit the game" to the one doing the quitting (the host)
70dac66de495ccb15765a4627c8550adefdf133f solves tons of warnings because of unset keys in .map …
=> Fix various console errors

Makefile, docker/docker-compose-dev-wsl.yaml, docker/nginx/nginx.wsl.conf
- port over changes from @karlromets to support windows WSL in docker
=> feat(dev): support for windows wsl in development

backend/api/session.go
Make sure we use the roomcode from the session token instead of event
=> fix(session): fix for getting back in via session token

backend/api/game.go, backend/api/pipe.go, backend/api/session.go, components/Admin/players.js, components/admin.js, components/buzzer.js, components/login.js, pages/index.js
- fix(backend): Team field is a pointer int that allows the json field to be null
- fix(frontend): adjust conditional in buzzer to not require picking team if the player is registered and has a team that isn't null
- chore(format): format buzzer.js, format conditional to remove unesseary else{}
- chore(clean): remove some unessesary console.debug
=> fix(session): player's team is kept when refreshing player page

.env, components/Login/Footer.jsx, components/Title/Version.jsx, package.json, public/locales/en/translation.json, public/locales/et/translation.json
=> feat(ui): add version indicator to home page

backend/api/health.go, backend/api/store-memory.go, backend/api/store-sqlite.go, backend/api/store.go
Fixes #152 
- Added `isHealthy` method to stores, which now makes `checkDatabase` universal
=> fix(health): support SQLite stores in checkDatabase

backend/api/game.go, src/components/Admin/Settings.jsx, src/components/BuzzerPage.jsx, src/components/BuzzerPopup.jsx
Buzzer sound settings were unusable on front-end due to missing props in back-end struct
=> fix(buzzer): add buzzer sound settings to struct

backend/api/buzzer.go, backend/api/client.go, backend/api/load-game.go, backend/api/store-sqlite.go, src/components/AdminPage.jsx
E2E tests passed, everything should be working as usual.
=> Fix back-end linter warnings

backend/api/errors.go, backend/api/session.go, public/locales/en/translation.json, public/locales/et/translation.json
Added checks to see who the quit is coming from.
Only allow quits from:
- current room hosts
- clients themselves
=> feat(security): add host/player validation for quit operations

public/locales/en/translation.json, public/locales/et/translation.json, src/components/Admin/GameLoader.jsx, src/components/AdminPage.jsx, src/lib/utils/files.js, src/lib/utils/index.ts
- chore: Move ui components for game upload into new file
- fix(ui): add subtitle to file upload to make it more obvious that the icon does something, matching style of Logo upload component
Looks like
E2E tests have passed
=> fix(ui): make file upload of game more obvious

doc/development.md
=> refactor(docs): update devdoc

src/components/AdminPage.jsx
=> Fix final round award points button

e2e/tests/home/home.spec.ts, package-lock.json, package.json, src/pages/index.jsx
Fixes #201
- **fix(Home): clear session data on room not found error**
- **chore(deps): bump playwright**
- **test(Home): add e2e test for clearing session cookie on room not found error**
=> Clear stale session cookie on room not found error

src/components/AdminPage.tsx, src/components/BuzzerPage.tsx, src/pages/game.tsx
=> fix: reload when refresh timer goes below 0, use ref for counter
